[package]
name = "mcmcpcp"
version = "0.1.0"
authors = ["Nipun Kumar <nipunkumar@outlook.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["router"] }
dioxus-native = { version = "0.7.0-rc.0" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "macros"] }
async-openai = "0.29.1"
anyhow = "1"
futures = "0.3"
pulldown-cmark = "0.11"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
