[bundle]
identifier = "io.github.nk"
publisher = "nk"
icon = ["assets/favicon.png"]

[application]

[web.app]

# HTML title tag content
title = "mcmcpcp"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
